spring:
  datasource:
    url: jdbc:mysql://114.55.32.110:3306/pattern_system?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/codeleven/patternsystem/dao/sqlmap/*
  type-handlers-package: com/codeleven/patternsystem/dao/typehandler
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      codeleven:
        patternsystem:
          dao: debug